=== rogeriogentil/starmx/src/main/resources/starmx-1.0.dtd
<!ELEMENT bean EMPTY >
<!ATTLIST bean id ID #REQUIRED >
<!ATTLIST bean class CDATA #REQUIRED >
<!ATTLIST bean factory-method CDATA #IMPLIED >

<!ELEMENT counter-monitor EMPTY >
<!ATTLIST counter-monitor init-threshold CDATA #REQUIRED>
<!ATTLIST counter-monitor notify (true | false) #REQUIRED>
<!ATTLIST counter-monitor offset CDATA #IMPLIED>
<!ATTLIST counter-monitor modulus CDATA #IMPLIED>
<!ATTLIST counter-monitor difference-mode (true | false) #IMPLIED>
	
<!ELEMENT execute ( (timer-info | notification-info), (process | processref)+ ) >
<!ATTLIST execute name ID #IMPLIED >
<!ATTLIST execute listener CDATA #IMPLIED >

<!ELEMENT factory-param EMPTY >
<!ATTLIST factory-param class CDATA #REQUIRED >
<!ATTLIST factory-param method CDATA #REQUIRED >

<!ELEMENT find-param EMPTY >
<!ATTLIST find-param agent-id CDATA #IMPLIED >
<!ATTLIST find-param index CDATA #IMPLIED >

<!ELEMENT gauge-monitor EMPTY >
<!ATTLIST gauge-monitor high-threshold CDATA #REQUIRED>
<!ATTLIST gauge-monitor low-threshold CDATA #REQUIRED>
<!ATTLIST gauge-monitor notify-high (true | false) #IMPLIED>
<!ATTLIST gauge-monitor notify-low (true | false) #IMPLIED>
<!ATTLIST gauge-monitor difference-mode (true | false) #IMPLIED>

<!ELEMENT jmx-param ( property* ) >
<!ATTLIST jmx-param protocol CDATA #IMPLIED >
<!ATTLIST jmx-param host CDATA #IMPLIED >
<!ATTLIST jmx-param port CDATA #IMPLIED >
<!ATTLIST jmx-param url-path CDATA #IMPLIED >
<!ATTLIST jmx-param service-url CDATA #IMPLIED >

<!ELEMENT jndi-param ( property* ) >
<!ATTLIST jndi-param jndi-name CDATA #REQUIRED >

<!ELEMENT mbean ( property* ) >
<!ATTLIST mbean id ID #REQUIRED >
<!ATTLIST mbean object-name CDATA #REQUIRED >
<!ATTLIST mbean interface CDATA #IMPLIED>
<!ATTLIST mbean mbeanserver IDREF #REQUIRED >

<!ELEMENT mbeanserver ( (find-param | jndi-param | jmx-param | factory-param)? ) >
<!ATTLIST mbeanserver id ID #REQUIRED >
<!ATTLIST mbeanserver lookup-type (platform|jndi|jmx|find|factory) #REQUIRED >

<!ELEMENT monitor-mbean ((counter-monitor | gauge-monitor | string-monitor), observed-object+ ) >
<!ATTLIST monitor-mbean	id ID #REQUIRED >
<!ATTLIST monitor-mbean	observed-attribute CDATA #REQUIRED >
<!ATTLIST monitor-mbean	granularity-period CDATA #REQUIRED >
<!ATTLIST monitor-mbean	object-name CDATA #REQUIRED >
<!ATTLIST monitor-mbean mbeanserver IDREF #REQUIRED >
	
<!ELEMENT notification-info EMPTY >
<!ATTLIST notification-info emitter-mbean-ref CDATA #REQUIRED >
<!ATTLIST notification-info event-type CDATA #IMPLIED >
<!ATTLIST notification-info event-class CDATA #IMPLIED >
<!ATTLIST notification-info event-handling (synch|asynch) #IMPLIED >

<!ELEMENT object EMPTY >
<!ATTLIST object name CDATA #REQUIRED >
<!ATTLIST object ref IDREF #REQUIRED >

<!ELEMENT observed-object EMPTY >
<!ATTLIST observed-object object-name CDATA #REQUIRED >

<!ELEMENT process ( object* ) >
<!ATTLIST process id ID #REQUIRED >
<!ATTLIST process policy-type CDATA #IMPLIED >
<!ATTLIST process policy-file CDATA #IMPLIED >
<!ATTLIST process javaclass CDATA #IMPLIED >

<!ELEMENT processref EMPTY >
<!ATTLIST processref refid IDREF #REQUIRED >

<!ELEMENT property ( #PCDATA ) >
<!ATTLIST property name CDATA #REQUIRED >

<!ELEMENT starmx ( mbeanserver*, monitor-mbean*, mbean*, bean*, process*, execute*, property*) >

<!ELEMENT string-monitor EMPTY >
<!ATTLIST string-monitor string-to-compare CDATA #REQUIRED>
<!ATTLIST string-monitor notify-match (true | false) #IMPLIED>
<!ATTLIST string-monitor notify-differ (true | false) #IMPLIED>
	
<!ELEMENT timer-info EMPTY >
<!ATTLIST timer-info interval CDATA #REQUIRED >
<!ATTLIST timer-info unit (second|minute|hour|day|week|month) #IMPLIED >
<!ATTLIST timer-info first-exec-time CDATA #IMPLIED >
<!ATTLIST timer-info first-exec-delay CDATA #IMPLIED >

=== rogeriogentil/starmx/src/test/resources/starmx.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE starmx PUBLIC "-//STAR Lab//StarMX Configuration DTD 1.0//EN" "../src/starmx-1.0.dtd" >
<starmx>
<!--
	<mbeanserver lookup-type="jndi" id="ms">
		<jndi-param jndi-name="jmx/invoker/RMIAdaptor">
			<property name="java.naming.factory.initial">org.jnp.interfaces.NamingContextFactory</property>
			<property name="java.naming.provider.url">jnp://localhost:1099</property>
			<property name="java.naming.factory.url.pkgs">org.jboss.naming:org.jnp.interfaces:org.jboss.naming.client</property>
		</jndi-param>
	</mbeanserver>	
-->	
	<mbeanserver id="ms" lookup-type="platform" />
<!-- 
	<mbeanserver id="ms2" lookup-type="jmx" >
	    <jmx-param service-url="service:jmx:rmi://localhost/jndi/rmi://localhost:1090/jmxconnector" />
	</mbeanserver>

	<monitor-mbean id="monitor1" observed-attribute="name" granularity-period="1000" mbeanserver="ms2" object-name="starmx:type=monitor,name=cm" >
		<counter-monitor init-threshold="100" notify="true" modulus="5" offset="8" difference-mode="true"/>
		<observed-object object-name="starmx:name=abc"/>
		<observed-object object-name="starmx:name=xyz"/>
		<observed-object object-name="starmx:name=def"/>
	</monitor-mbean>
	
	<monitor-mbean id="monitor2" observed-attribute="name" granularity-period="1000" mbeanserver="ms2" object-name="starmx:type=monitor,name=gm" >
		<gauge-monitor high-threshold="100" low-threshold="10" notify-high="true" notify-low="false" difference-mode="true"/>
		<observed-object object-name="starmx:name=abc"/>
		<observed-object object-name="starmx:name=xyz"/>
		<observed-object object-name="starmx:name=def"/>
	</monitor-mbean>

	<monitor-mbean id="monitor3" observed-attribute="name" granularity-period="1000" mbeanserver="ms2" object-name="starmx:type=monitor,name=sm" >
		<string-monitor string-to-compare="aabbcc" notify-differ="true" notify-match="false"/>
		<observed-object object-name="starmx:name=abc"/>
		<observed-object object-name="starmx:name=xyz"/>
		<observed-object object-name="starmx:name=def"/>
	</monitor-mbean>
-->
	<mbean id="myBean1" object-name="starmx:name=mb1,instance=1" mbeanserver="ms" />

	<mbean id="myBean2" object-name="starmx:name=mb2" mbeanserver="ms" />
	<bean id="sb" class="util.SimpleBean" factory-method="createInstance" />
	
	<process id="policy1" policy-type="spl" policy-file="policy1.spl">
		<object name="mb1" ref="myBean1" />
		<object name="mb2" ref="myBean2" />
	</process>

	<process id="policy2" policy-type="spl" policy-file="policy2.spl">
		<object name="sb" ref="sb" />
	</process>

	<process id="policy3" policy-type="spl" policy-file="policy3.spl">
		<object name="mb1" ref="myBean1" />
		<object name="mb2" ref="myBean2" />
		<object name="sb" ref="sb" />
	</process>

	<process id="policy4" policy-type="spl" policy-file="sample_policy.spl" >
		<object name="mb2" ref="myBean2" />
		<object name="mb1" ref="myBean1" /> 
	</process> 


	<execute >
		<timer-info interval="5" unit="second" /> 
		
		<processref refid="policy3" />		

	</execute>
	
<!-- 		
	<policy name="policy1" type="spl" file="policy1.spl">

		<object name="mb1" ref="myBean1" />
		<object name="mb2" ref="myBean2" />

		<evaluate mechanism="timer" >
			<timer-info interval="4" unit="second" /> 
		</evaluate>
	</policy>

	<policy name="policy2" type="spl" file="policy2.spl">

		<object name="sb" ref="sb" />
		<evaluate mechanism="enforced" />
		
	</policy>
 -->

<!--
	<property name="starmx.mbean.history_size">10</property>
	<property name="starmx.mbean.add_to_history_strategy">anyRead/firstReadInPolicyExecution(default)</property>
	<property name="starmx.mbean.cache_attr_in_policy_execution">true/false</property>
	<property name="starmx.mbean.convert_objectname_to_mbean">true(default)/false</property>
	<property name="starmx.log.dir">C:\Java\jboss-5.0.0.Beta4\server\default\log</property>
	<property name="starmx.policy.onError">retry</property>
	<property name="starmx.policy.onError.retryCount">2</property>
-->
	<property name="starmx.log.level">debug</property>
 
</starmx>

=== rogeriogentil/starmx/src/test/resources/notification/starmx.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE starmx PUBLIC "-//STAR Lab//StarMX Configuration DTD 1.0//EN" "main/resources/starmx-1.0.dtd" >
<starmx>

	<mbeanserver id="ms" lookup-type="platform" />
<!--     
	<mbeanserver id="ms" lookup-type="jmx" >
		<jmx-param service-url="service:jmx:rmi://localhost/jndi/rmi://localhost:1090/jmxconnector" />
	</mbeanserver>
-->
	<mbean id="mbean11" object-name="starmx:name=mb1,instance=1" mbeanserver="ms" />
	<mbean id="mbean12" object-name="starmx:name=mb1,instance=2" mbeanserver="ms" />
	<mbean id="mbean1" object-name="starmx:name=mb1,*" mbeanserver="ms" />

	<mbean id="mbean2" object-name="starmx:name=mb2" mbeanserver="ms" />
  
	<process id="policy2" policy-type="spl" policy-file="Policy2.spl">
		<object name="mb1_1" ref="mbean11" />
	</process>
 
	<process id="policy3" policy-type="spl" policy-file="Policy3.spl">
		<object name="mb1_2" ref="mbean12" />
	</process>
  
	<process id="policy4" policy-type="spl" policy-file="Policy4.spl">
		<object name="mb2" ref="mbean2" />
	</process>
	
	<execute >
		<timer-info interval="10" unit="second" /> 
		<processref refid="policy2" />		
	</execute>

	<execute >
		<timer-info interval="5" unit="second" /> 
		<processref refid="policy3" />		
	</execute>
	<execute >
		<notification-info event-type="starmx.test.event1" 
								emitter-mbean-ref="mbean1" 
								event-handling="synch"	/>			
		<processref refid="policy4" />		
	</execute>
	
<!-- 
	<process name="policy5">
		<splfile>notification/Policy4.spl</splfile>

		<object name="mb2" type="mbean" ref="mbean2" />
		
		<evaluate mechanism="timer" >
			<timer-info interval="5" unit="second"/> 
		</evaluate>
	</process>
-->
<!-- 
	<property name="starmx.mbean.history_size">10</property>
	<property name="starmx.mbean.add_to_history_strategy">anyRead/firstReadInPolicyExecution(default)</property>
	<property name="starmx.mbean.cache_attr_in_policy_execution">true/false</property>
	<property name="starmx.mbean.convert_objectname_to_mbean">true(default)/false</property>
	 -->
</starmx>

=== rogeriogentil/starmx/src/test/resources/starmx-sample2.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE starmx PUBLIC "-//STAR Lab//StarMX Configuration DTD 1.0//EN" "../src/starmx-1.0.dtd" >
<starmx>
	<mbeanserver id="s1" lookup-type="platform" />

	<mbeanserver id="s2" lookup-type="find">
		<find-param agent-id="" index="" />
	</mbeanserver>

	<mbeanserver id="s3" lookup-type="jndi">
		<jndi-param jndi-name="">
			<property name="username">reza</property>
			<property name="password">123</property>
		</jndi-param>
	</mbeanserver>

	<mbeanserver id="s4" lookup-type="factory">
		<factory-param class="" method="" />
	</mbeanserver>

	<mbeanserver id="wls_ms1" lookup-type="jmx">
		<jmx-param
			service-url="service:jmx:rmi:///jndi/iiop://localhost:7001/weblogic.management.mbeanservers.runtime">
			<property name="java.naming.security.principal">weblogic</property>
			<property name="java.naming.security.credentials">weblogic</property>
		</jmx-param>
	</mbeanserver>

	<mbeanserver id="wls_ms2" lookup-type="jmx">
		<jmx-param protocol="t3" host="localhost" port="7001" url-path="/jndi/weblogic.management.mbeanservers.domainruntime">
			<property name="java.naming.security.principal">weblogic</property>
			<property name="java.naming.security.credentials">weblogic</property>
			<property name="jmx.remote.protocol.provider.pkgs">weblogic.management.remote</property>
		</jmx-param>
	</mbeanserver>

	<mbeanserver id="jboss_ms" lookup-type="jmx" >
	    <jmx-param service-url="service:jmx:rmi://localhost/jndi/rmi://localhost:1090/jmxconnector" />
	</mbeanserver>

	<mbean id="mbean1" object-name="domain:key1=val1,key2=val2"
		mbeanserver="s2" interface="optional - mbean implemented interface">
		<!--OPTIONAL SECTION-->
		<property name="starmx.mbean.convert_objectname_to_mbean">false</property>
		<property name="testprop">val</property>
	</mbean>
	
	<mbean id="myBeanList" object-name="domain:key1=val1,*"	mbeanserver="s4" />
	
	<bean id="aBean" class="mbeangen.Simple" />
	
<!-- 	<webservice id="ws1" wsdl="" />  -->
	
	<policy name="policy1" type="spl" file="Policy1.spl">
		<!-- MBeans or POJOs to be injected to the policy at runtime -->
		<!--
			<object name="obj1" type="mbean(default) | bean | spring-bean |
			webservice" ref="mbean1" />
		-->
		<object name="obj1" ref="mbean1" />
		<object name="obj2" ref="aBean" />
		<object name="obj3" ref="myBeanList" />
		<!--
			for Spring integration look at the WebWork/Struts and Spring
			integration
		-->
		<!--
			the notification object is injected into the policy at execution
			runtime
		-->
		<evaluate mechanism="timer">
			<!--
				<timer-info interval="5"
				unit="second(default)|minute|hour|day|week|month"
				{first-exec-time="18:00" or first-exec-delay="5" second}/>
			-->
			<timer-info interval="5" unit="second" first-exec-time="12:00" />
		</evaluate>
	</policy>
	<policy name="policy2" type="spl" file="Policy2.spl">
		<object name="obj1" ref="mbean1" />
		<evaluate mechanism="notification">
			<notification-info event-type="EVENT_TYPE1,EVENT_TYPE2"
				emitter-mbean="myBean" event-handling="synch"
				event-class="" />
		</evaluate>
	</policy>
	<property name="starmx.mbean.history_size">10</property>
	<property name="starmx.mbean.add_to_history_strategy">anyRead/firstReadInPolicyExecution(default)</property>
	<property name="starmx.mbean.cache_attr_in_policy_execution">true/false</property>
	<property name="starmx.mbean.convert_objectname_to_mbean">true(default)/false</property>

	<property name="starmx.log.level">debug | info | warn | error | fatal</property>
	<property name="starmx.log.dir">C:\Java\jboss-5.0.0.Beta4\server\default\log</property>

	<property name="starmx.policy.onError">disable(default) | retry</property>
	<property name="starmx.policy.onError.retryCount">n (default = 0)</property>
	<property name="starmx.policy.adapter.spl">org.starmx.policy.adapter.imperius.ImperiusPolicyAdapter</property>
</starmx>

=== rogeriogentil/starmx/src/test/resources/proxy/starmx.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE starmx PUBLIC "-//STAR Lab//StarMX Configuration DTD 1.0//EN" "../../src/starmx-1.0.dtd" >
<starmx>
	<mbeanserver id="ms" lookup-type="platform" />
<!--  	
	<mbeanserver lookup-type="jndi" id="s3">
		<jndi-param jndi-name="jmx/invoker/RMIAdaptor">
			<property name="java.naming.factory.initial">org.jnp.interfaces.NamingContextFactory</property>
			<property name="java.naming.provider.url">jnp://localhost:1099</property>
			<property name="java.naming.factory.url.pkgs">org.jboss.naming:org.jnp.interfaces:org.jboss.naming.client</property>
		</jndi-param>
	</mbeanserver>
-->
	<mbean id="mbean11" object-name="starmx:name=mb1,instance=1" mbeanserver="ms" interface="util.MBean1MBean"/>
	<mbean id="mbean12" object-name="starmx:name=mb1,instance=2" mbeanserver="ms" interface="util.MBean1MBean"/>
	<mbean id="mbean1" object-name="starmx:name=mb1,*" mbeanserver="ms" />

	<mbean id="mbean2" object-name="starmx:name=mb2" mbeanserver="ms" />
  
  	<execute >
		<timer-info interval="3" unit="second"/> 
		<process id="policy1" policy-type="spl" policy-file="Policy1.spl">
			<object name="mb1_1" ref="mbean11" />
			<object name="mb1_2" ref="mbean12" />
		</process>
  	</execute>

</starmx>

=== rogeriogentil/starmx/src/test/resources/thirdparty/weblogic/starmx.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE starmx PUBLIC "-//STAR Lab//StarMX Configuration DTD 1.0//EN" "../src/starmx-1.0.dtd" >
<starmx>
 
	<mbeanserver id="wls_remote_ms1" lookup-type="jmx">
		<jmx-param protocol="t3" host="localhost" port="7001" url-path="/jndi/weblogic.management.mbeanservers.domainruntime">
			<property name="java.naming.security.principal">weblogic</property>
			<property name="java.naming.security.credentials">weblogic</property>
			<property name="jmx.remote.protocol.provider.pkgs">weblogic.management.remote</property>
		</jmx-param>
	</mbeanserver>

<!--  
	This does not work !!! why?
	<mbeanserver id="wls_ms2" lookup-type="jmx">
		<jmx-param
			service-url="service:jmx:rmi:///jndi/iiop://localhost:7001/weblogic.management.mbeanservers.domainruntime">
			<property name="java.naming.security.principal">weblogic</property>
			<property name="java.naming.security.credentials">weblogic</property>
		</jmx-param>
	</mbeanserver>
-->
<!--   
	<mbeanserver id="wls_local_ms1" lookup-type="jndi">
		<jndi-param jndi-name="java:comp/jmx/runtime" />
	</mbeanserver>
-->
	<mbeanserver id="pms" lookup-type="platform" />
 
	<mbean id="wlServiceMBean" 
		object-name="com.bea:Name=DomainRuntimeService,Type=weblogic.management.mbeanservers.domainruntime.DomainRuntimeServiceMBean" 
		mbeanserver="wls_remote_ms1" />
<!-- 
	<mbean id="wlServiceMBean" 
		object-name="com.bea:Name=RuntimeService,Type=weblogic.management.mbeanservers.runtime.RuntimeServiceMBean" 
		mbeanserver="wls_local_ms1" />
 -->
	<mbean id="myBean1" object-name="starmx:name=mb1,instance=1" mbeanserver="pms" />
	<mbean id="myBean2" object-name="starmx:name=mb2" mbeanserver="pms" />

	<policy name="policy1" type="spl" file="test_wl.spl">

		<object name="mb1" ref="myBean1" />
		<object name="mb2" ref="myBean2" />
		<object name="wlrsmb" ref="wlServiceMBean" />

		<evaluate mechanism="timer" >
			<timer-info interval="3" unit="second" /> 
		</evaluate>
	</policy>

<!--
	<property name="starmx.mbean.history_size">10</property>
	<property name="starmx.mbean.add_to_history_strategy">anyRead/firstReadInPolicyExecution(default)</property>
	<property name="starmx.mbean.cache_attr_in_policy_execution">true/false</property>
	<property name="starmx.mbean.convert_objectname_to_mbean">true(default)/false</property>
	<property name="starmx.log.dir">C:\Java\jboss-5.0.0.Beta4\server\default\log</property>
-->
	<property name="starmx.log.level">debug</property>
	<property name="starmx.policy.onError">retry</property>
	<property name="starmx.policy.onError.retryCount">2</property>

</starmx>

=== rogeriogentil/starmx/src/test/resources/mxbean/starmx.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE starmx PUBLIC "-//STAR Lab//StarMX Configuration DTD 1.0//EN" "../../src/starmx-1.0.dtd" >
<starmx>

	<mbeanserver id="pms" lookup-type="platform" />
<!--   
	<mbeanserver id="ms" lookup-type="jmx" >
		<jmx-param service-url="service:jmx:rmi://localhost/jndi/rmi://localhost:1090/jmxconnector" />
	</mbeanserver>
-->
	<!-- mbean id="mbean1" object-name="starmx:name=mb1,instance=1" mbeanserver="pms" /-->

	<mbean id="runtimeMXbean" object-name="java.lang:type=Runtime" mbeanserver="pms" interface="java.lang.management.RuntimeMXBean"/>
	<mbean id="classLoadingMXBean" object-name="java.lang:type=ClassLoading" mbeanserver="pms" interface="java.lang.management.ClassLoadingMXBean"/>
	<mbean id="memoryMXBean" object-name="java.lang:type=Memory" mbeanserver="pms" interface="java.lang.management.MemoryMXBean"/>
	<mbean id="threadMXBean" object-name="java.lang:type=Threading" mbeanserver="pms" interface="java.lang.management.ThreadMXBean"/>
	<mbean id="operatingSystemMXBean" object-name="java.lang:type=OperatingSystem" mbeanserver="pms" interface="java.lang.management.OperatingSystemMXBean"/>

	<mbean id="compilationMXBean" object-name="java.lang:type=Compilation" mbeanserver="pms" interface="java.lang.management.CompilationMXBean"/>
	<mbean id="memoryPoolMXBean" object-name="java.lang:type=MemoryPool,name=Tenured Gen" mbeanserver="pms" interface="java.lang.management.MemoryPoolMXBean"/>

	<execute >
		<timer-info interval="2" unit="second"/> 
		<process id="samplePolicy" policy-type="spl" policy-file="policy.spl">
			<!-- object name="mb1" ref="mbean1" /-->
			<object name="rtmxb" ref="runtimeMXbean" />
			<object name="clmxb" ref="classLoadingMXBean" />
		 	<object name="memmxb" ref="memoryMXBean" />
			<object name="thrmxb" ref="threadMXBean" />
			<object name="osmxb" ref="operatingSystemMXBean" />
			<object name="cmxb" ref="compilationMXBean" />
			<object name="mpmxb" ref="memoryPoolMXBean" />
	
		</process>
	</execute>
	
 	<property name="starmx.log.level">info</property>
 
</starmx>

=== rogeriogentil/starmx/src/test/resources/starmx-sample.xml
<!-- THIS IS A SAMPLE STARMX.XML FILE, DESIGNED FOR ILLUSTRATION PURPOSE ONLY -->
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE starmx PUBLIC "-//STAR Lab//StarMX Configuration DTD 1.0//EN" "starmx-1.0.dtd">
<starmx>

    <mbeanserver id="wls_remote_ms" lookup-type="jmx">
        <jmx-param protocol="t3" host="localhost" port="7001"
            url-path="/jndi/weblogic.management.mbeanservers.domainruntime">
            <property name="java.naming.security.principal">weblogic</property>
            <property name="java.naming.security.credentials">weblogic</property>
            <property name="jmx.remote.protocol.provider.pkgs">weblogic.management.remote</property>
        </jmx-param>
    </mbeanserver>

    <mbean id="wlServiceMBean"
        object-name="com.bea:Name=DomainRuntimeService,
            Type=weblogic.management.mbeanservers.domainruntime.DomainRuntimeServiceMBean"
        mbeanserver="wls_remote_ms" />

    <mbean id="mbean1" object-name="starmx:name=mb1" mbeanserver="wls_remote_ms" />
    <mbean id="mbean2" object-name="starmx:name=mb2" mbeanserver="wls_remote_ms" />

	<bean id="mailSender" class="util.MailSender" />
	
    <monitor-mbean  id="gaugeMonitor"
                    observed-attribute="size" granularity-period="1000"
                    mbeanserver="wls_remote_ms"
                    object-name="starmx:type=monitor,name=gm" >
        <gauge-monitor high-threshold="100" low-threshold="10" notify-high="true" />
        <observed-object object-name="starmx:type=Control,name=*"/>
    </monitor-mbean>

    <process id="proc1" policy-type="spl" policy-file="policy1.spl">
        <object name="wldrsmb" ref="wlServiceMBean" />
        <object name="mailSender" ref="mailSender" />
    </policy>

    <execute >
        <timer-info interval="30" unit="second" />

        <processref refid="proc1" />
        <process id="proc2" policy-type="drl" policy-file="policy2.drl">
            <object name="mb1" ref="mbean1" />
            <object name="mb2" ref="mbean2" />
        </process>
    </execute>

    <execute >
        <notification-info  emitter-mbean="gaugeMonitor"
                            event-type="jmx.monitor.gauge.high" />

        <processref refid="proc1" />
        <process id="proc3" javaclass="test.MySampleProcess">
            <object name="monitor" ref="gaugeMonitor" />
        </process>
    </execute>

    <property name="starmx.log.level">warn</property>
    <property name="starmx.log.dir">/starmx/log</property>
    <property name="starmx.policy.adapter.drl">sample.policy.DroolsPolicyAdapter</property>
</starmx>

=== rogeriogentil/starmx/src/test/resources/scope/starmx.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE starmx PUBLIC "-//STAR Lab//StarMX Configuration DTD 1.0//EN" "starmx-1.0.dtd" >
<starmx>

	<mbeanserver id="ms" lookup-type="platform" />
<!--     
	<mbeanserver id="ms" lookup-type="jmx" >
		<jmx-param service-url="service:jmx:rmi://localhost/jndi/rmi://localhost:1090/jmxconnector" />
	</mbeanserver>
-->
	<mbean id="mbean11" object-name="starmx:name=mb1,instance=1" mbeanserver="ms" />
	<mbean id="mbean12" object-name="starmx:name=mb1,instance=2" mbeanserver="ms" />
	<mbean id="mbean1" object-name="starmx:name=mb1,*" mbeanserver="ms" />

	<mbean id="mbean2" object-name="starmx:name=mb2" mbeanserver="ms" />

	<execute>
		<timer-info interval="3" unit="second" />
		<process id="policy1" policy-type="spl" policy-file="Policy1.spl">
			<object name="mb1_1" ref="mbean11" />
		</process>
	</execute>
<!--  
	<policy name="policy2">
		<splfile>Policy2.spl</splfile>

		<object name="mb1_1" ref="mbean11" />

		<evaluate mechanism="timer" >
			<timer-info interval="10" unit="second"/> 
		</evaluate>
	</policy>

	<policy name="policy3">
		<splfile>Policy3.spl</splfile>

		<object name="mb1_2" ref="mbean12" />

		<evaluate mechanism="timer" >
			<timer-info interval="5" unit="second"/> 
		</evaluate>
	</policy>
  
	<policy name="policy4">
		<splfile>Policy4.spl</splfile>

		<object name="mb2" type="mbean" ref="mbean2" />
		
		<evaluate mechanism="notification" >
			<notification-info event-type="starmx.test.event1" 
								emitter-mbean="mbean1" 
								event-handling="asynch"	/>			
		</evaluate>
	</policy>
	 -->
<!-- 
	<policy name="policy5">
		<splfile>Policy4.spl</splfile>

		<object name="mb2" type="mbean" ref="mbean2" />
		
		<evaluate mechanism="timer" >
			<timer-info interval="5" unit="second"/> 
		</evaluate>
	</policy>
-->
	<property name="starmx.mbean.history_size">10</property>
	<property name="starmx.mbean.add_to_history_strategy">anyRead/firstReadInPolicyExecution(default)</property>
	<property name="starmx.mbean.cache_attr_in_policy_execution">true/false</property>
	<property name="starmx.mbean.convert_objectname_to_mbean">true(default)/false</property>
</starmx>
