=== rogeriogentil/starmx/src/main/resources/starmx-1.0.dtd
<!ELEMENT bean EMPTY >
<!ATTLIST bean id ID #REQUIRED >
<!ATTLIST bean class CDATA #REQUIRED >
<!ATTLIST bean factory-method CDATA #IMPLIED >

<!ELEMENT counter-monitor EMPTY >
<!ATTLIST counter-monitor init-threshold CDATA #REQUIRED>
<!ATTLIST counter-monitor notify (true | false) #REQUIRED>
<!ATTLIST counter-monitor offset CDATA #IMPLIED>
<!ATTLIST counter-monitor modulus CDATA #IMPLIED>
<!ATTLIST counter-monitor difference-mode (true | false) #IMPLIED>
	
<!ELEMENT execute ( (timer-info | notification-info), (process | processref)+ ) >
<!ATTLIST execute name ID #IMPLIED >
<!ATTLIST execute listener CDATA #IMPLIED >

<!ELEMENT factory-param EMPTY >
<!ATTLIST factory-param class CDATA #REQUIRED >
<!ATTLIST factory-param method CDATA #REQUIRED >

<!ELEMENT find-param EMPTY >
<!ATTLIST find-param agent-id CDATA #IMPLIED >
<!ATTLIST find-param index CDATA #IMPLIED >

<!ELEMENT gauge-monitor EMPTY >
<!ATTLIST gauge-monitor high-threshold CDATA #REQUIRED>
<!ATTLIST gauge-monitor low-threshold CDATA #REQUIRED>
<!ATTLIST gauge-monitor notify-high (true | false) #IMPLIED>
<!ATTLIST gauge-monitor notify-low (true | false) #IMPLIED>
<!ATTLIST gauge-monitor difference-mode (true | false) #IMPLIED>

<!ELEMENT jmx-param ( property* ) >
<!ATTLIST jmx-param protocol CDATA #IMPLIED >
<!ATTLIST jmx-param host CDATA #IMPLIED >
<!ATTLIST jmx-param port CDATA #IMPLIED >
<!ATTLIST jmx-param url-path CDATA #IMPLIED >
<!ATTLIST jmx-param service-url CDATA #IMPLIED >

<!ELEMENT jndi-param ( property* ) >
<!ATTLIST jndi-param jndi-name CDATA #REQUIRED >

<!ELEMENT mbean ( property* ) >
<!ATTLIST mbean id ID #REQUIRED >
<!ATTLIST mbean object-name CDATA #REQUIRED >
<!ATTLIST mbean interface CDATA #IMPLIED>
<!ATTLIST mbean mbeanserver IDREF #REQUIRED >

<!ELEMENT mbeanserver ( (find-param | jndi-param | jmx-param | factory-param)? ) >
<!ATTLIST mbeanserver id ID #REQUIRED >
<!ATTLIST mbeanserver lookup-type (platform|jndi|jmx|find|factory) #REQUIRED >

<!ELEMENT monitor-mbean ((counter-monitor | gauge-monitor | string-monitor), observed-object+ ) >
<!ATTLIST monitor-mbean	id ID #REQUIRED >
<!ATTLIST monitor-mbean	observed-attribute CDATA #REQUIRED >
<!ATTLIST monitor-mbean	granularity-period CDATA #REQUIRED >
<!ATTLIST monitor-mbean	object-name CDATA #REQUIRED >
<!ATTLIST monitor-mbean mbeanserver IDREF #REQUIRED >
	
<!ELEMENT notification-info EMPTY >
<!ATTLIST notification-info emitter-mbean-ref CDATA #REQUIRED >
<!ATTLIST notification-info event-type CDATA #IMPLIED >
<!ATTLIST notification-info event-class CDATA #IMPLIED >
<!ATTLIST notification-info event-handling (synch|asynch) #IMPLIED >

<!ELEMENT object EMPTY >
<!ATTLIST object name CDATA #REQUIRED >
<!ATTLIST object ref IDREF #REQUIRED >

<!ELEMENT observed-object EMPTY >
<!ATTLIST observed-object object-name CDATA #REQUIRED >

<!ELEMENT process ( object* ) >
<!ATTLIST process id ID #REQUIRED >
<!ATTLIST process policy-type CDATA #IMPLIED >
<!ATTLIST process policy-file CDATA #IMPLIED >
<!ATTLIST process javaclass CDATA #IMPLIED >

<!ELEMENT processref EMPTY >
<!ATTLIST processref refid IDREF #REQUIRED >

<!ELEMENT property ( #PCDATA ) >
<!ATTLIST property name CDATA #REQUIRED >

<!ELEMENT starmx ( mbeanserver*, monitor-mbean*, mbean*, bean*, process*, execute*, property*) >

<!ELEMENT string-monitor EMPTY >
<!ATTLIST string-monitor string-to-compare CDATA #REQUIRED>
<!ATTLIST string-monitor notify-match (true | false) #IMPLIED>
<!ATTLIST string-monitor notify-differ (true | false) #IMPLIED>
	
<!ELEMENT timer-info EMPTY >
<!ATTLIST timer-info interval CDATA #REQUIRED >
<!ATTLIST timer-info unit (second|minute|hour|day|week|month) #IMPLIED >
<!ATTLIST timer-info first-exec-time CDATA #IMPLIED >
<!ATTLIST timer-info first-exec-delay CDATA #IMPLIED >

=== rogeriogentil/starmx/src/test/resources/monitor/starmx.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE starmx PUBLIC "-//STAR Lab//StarMX Configuration DTD 1.0//EN" "../../src/starmx-1.0.dtd" >
<starmx>
	<mbeanserver id="ms" lookup-type="platform" />
<!-- 
	<monitor-mbean id="monitor1" observed-attribute="Value" granularity-period="1000" mbeanserver="ms" object-name="starmx:type=monitor,name=gm" >
		<gauge-monitor high-threshold="20.5" low-threshold="8.1" notify-high="true" notify-low="true" difference-mode="false"/>
		<observed-object object-name="starmx:name=mb1,instance=1"/>
	</monitor-mbean>
-->
	<monitor-mbean id="monitor2" observed-attribute="Value" granularity-period="1000" mbeanserver="ms" object-name="starmx:type=monitor,name=cm" >
		<counter-monitor init-threshold="20" notify="true" difference-mode="false"/>
		<observed-object object-name="starmx:name=mb1,instance=1"/>
	</monitor-mbean>

	<execute >
		<notification-info emitter-mbean-ref="monitor2" event-type="jmx.monitor.counter.threshold"/>
		<process id="p1" javaclass="monitor.MonitorNotifiedProcess" />
	</execute>

<!--
	<property name="starmx.mbean.history_size">10</property>
	<property name="starmx.mbean.add_to_history_strategy">anyRead/firstReadInPolicyExecution(default)</property>
	<property name="starmx.mbean.cache_attr_in_policy_execution">true/false</property>
	<property name="starmx.mbean.convert_objectname_to_mbean">true(default)/false</property>
	<property name="starmx.log.dir">C:\Java\jboss-5.0.0.Beta4\server\default\log</property>
	<property name="starmx.policy.onError">retry</property>
	<property name="starmx.policy.onError.retryCount">2</property>
-->
	<property name="starmx.log.level">debug</property>
 
</starmx>

=== rogeriogentil/starmx/src/test/resources/javaprocess/starmx.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE starmx PUBLIC "-//STAR Lab//StarMX Configuration DTD 1.0//EN" "../../src/starmx-1.0.dtd" >
<starmx>
<!--
	<mbeanserver lookup-type="jndi" id="ms">
		<jndi-param jndi-name="jmx/invoker/RMIAdaptor">
			<property name="java.naming.factory.initial">org.jnp.interfaces.NamingContextFactory</property>
			<property name="java.naming.provider.url">jnp://localhost:1099</property>
			<property name="java.naming.factory.url.pkgs">org.jboss.naming:org.jnp.interfaces:org.jboss.naming.client</property>
		</jndi-param>
	</mbeanserver>	
-->	
	<mbeanserver id="ms" lookup-type="platform" />

	<mbean id="threadMXBean" object-name="java.lang:type=Threading" mbeanserver="ms" interface="java.lang.management.ThreadMXBean"/>
	<mbean id="myBean1" object-name="starmx:name=mb1,instance=1" mbeanserver="ms" interface="util.MBean1MBean"/>
	<mbean id="myBean2" object-name="starmx:name=mb2" mbeanserver="ms" />

	<mbean id="myBean1List" object-name="starmx:name=mb1,*" mbeanserver="ms" interface="util.MBean1MBean"/>

	<bean id="sb" class="util.SimpleBean" factory-method="createInstance" />
	
	<process id="p2" javaclass="javaprocess.SampleProcess2">
		<object name="mb1" ref="myBean1" />
 		<object name="sb" ref="sb" />  
 		<object name="threadMXBean" ref="threadMXBean" />  
	</process>

	<process id="p1" javaclass="javaprocess.SampleProcess">
		<object name="mb1List" ref="myBean1List"/>
	</process>

	<execute >
		<timer-info interval="5" unit="second" /> 
		<processref refid="p1" />		
		<processref refid="p2" />		
	</execute>
	
	<property name="starmx.log.level">debug</property>
 
</starmx>
